import type { Metadata } from "next";
import 'bootstrap/dist/css/bootstrap.min.css';
import NavBar from "@/components/Header/NavBar";

export const metadata: Metadata = {
  title: "Smart Shopper - AI Shopping Assistant",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
      <html lang="en">
        <body className="bg-dark">
          <NavBar />
          {children}
        </body>
      </html>
  );
}
