import type { Metadata } from "next";
import 'bootstrap/dist/css/bootstrap.min.css';
import '../public/styles/Custom.scss';
import { Toaster } from 'sonner';
import NavBar from "@/components/Header/NavBar";
import { cookies } from "next/headers";

export const metadata: Metadata = {
  title: "Smart Shopper - AI Shopping Assistant",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const cookie = cookies().get('token');
  return (
      <html lang="en">
        <body className="bg-dark">
          <NavBar cookie={cookie} />
          {children}
          <Toaster />
        </body>
      </html>
  );
}
